import { Knex } from 'knex'

declare module 'knex/types/tables' {
	export interface Tables {
		produto: {
			id
			altura_master
			altura_unidade
			ativo
			camada_norma_palete
			categoria_armazenagem_id
			codigo
			codigoerp
			comprimento_master
			comprimento_unidade
			controla_lote
			controla_validade
			controle_em_metro
			custo
			custo_divergencia
			data_integracao
			descricao
			dun
			ean
			embalagem
			empresa_id
			estoque_desconsiderado
			exclusivo_crossdocking
			induz_lote
			largura_master
			largura_unidade
			lastro_norma_palete
			marca
			multiplo
			nivel_maximo_armazenagem
			peso_master
			peso_unidade
			peso_variavel
			pode_informar_codigo_interno
			qtde_avaria_gerencial
			qtde_gerencial
			qtde_reservada
			qtunit
			qtunitcx
			shel_life
			shel_life_devolucao
			shel_life_entrada
			status_integracao
			tipo_separacao
			tolerancia_shel_life
			tolerancia_shel_life_devolucao
			tolerancia_shel_life_entrada
			total_norma_palete
			usa_lote_unico_no_picking
			usa_picking
			volume_master
			volume_unidade
			kit_id
			data_ultimo_inventario
			numero_ultimo_inventario
			tem_inventario_ativo
			usa_validade_unica_no_picking
			usuario_id_alteracao
			codigo_montagem
			codigo_referencia
			curva_acesso
			curva_venda
			produto_preco_id
			fornecedor_id
			local_produto_erp
			enviado_wcs
			validar_dados_logisticos
		}
		movimentacao: {
			id
			qtde_ocorrencias
			abastecimento_id
			antecipada
			atrasada
			box
			cliente
			codigo_conferente
			codigo_embalador
			codigo_separador
			conferido
			data_embalagem
			data_estorno
			data_fabricacao
			data_fim_conferencia
			data_fim_separacao
			data_finalizacao
			data_geracao
			data_inicio_conferencia
			data_inicio_separacao
			data_integracao
			data_liberacao
			data_validade
			empresa_id
			endereco_final
			estoque_id
			estornado
			gerou_pendencia_estoque
			id_erp
			id_usuario_geracao
			induziu_lote
			lote
			maior_predio
			numero_caixa_et
			numero_carga
			numero_conferencia_entrada
			numero_et
			numeroom
			numeroop
			numero_palete
			numero_pedido
			numero_sequencia_entrega
			numero_sequencia_montagem
			numero_transacao
			numero_unitizador
			observacao_item
			ordem
			qt
			qt_estoque_ae
			qtconferida
			qtcx
			qtorig
			qtseparada
			qtun
			recebimento_liberado_venda
			reentrega
			separado
			sequencia_flow_rack_convocar
			situacao
			status_integracao
			tipo
			tipo_operacao
			tipo_separacao_produto
			usuario_estorno_id
			volume_id
			box_id
			conferencia_id
			endereco_id
			endereco_origem_id
			etiqueta_ual_id
			mapa_separacao_id
			produto_id
			data_embarque_palete
		}
	}
}
